"""生成扩充后的规则 JSON 定义与检查函数代码骨架"""
import os, json

BASE = os.path.join('seo_audit', 'auditor', 'rules')
SEVERITY_ORDER = ['critical', 'important', 'info']
CATEGORY_NAMES = {
    'crawl_index': '抓取与索引',
    'tdk': 'TDK 优化',
    'content_quality': '内容质量',
    'technical_seo': '技术 SEO',
    'performance': '性能优化',
    'mobile': '移动友好',
    'structured_data': '结构化数据',
}


def make_rule(rid, name, cat, sev, weight, desc, fix, check_fn, enabled=True):
    return {
        "id": rid,
        "name": name,
        "category": cat,
        "severity": sev,
        "weight": weight,
        "description": desc,
        "fix_advice": fix,
        "check_function": check_fn,
        "enabled": enabled,
    }


# ========== 1. 抓取与索引（现有 12 → 目标 42） ==========
def build_crawl_index(existing):
    rules = list(existing)
    existing_ids = {r['id'] for r in rules}
    additions = [
        make_rule('robots_sitemap_declared', 'robots.txt 声明 Sitemap 位置', 'crawl_index', 'info', 'low',
                  '检查 robots.txt 是否声明了 Sitemap 位置，帮助搜索引擎发现',
                  '在 robots.txt 文件末尾添加 Sitemap: https://example.com/sitemap.xml 行',
                  'check_robots_sitemap_declared'),
        make_rule('robots_crawl_delay', 'robots.txt 爬取延迟配置合理', 'crawl_index', 'info', 'low',
                  '检查 robots.txt 中 Crawl-delay 配置是否过大',
                  '如设置了 Crawl-delay，建议不超过 10 秒，避免影响抓取效率',
                  'check_robots_crawl_delay'),
        make_rule('robots_no_wildcard_block', 'robots.txt 未过度屏蔽全站', 'crawl_index', 'critical', 'high',
                  '检查 robots.txt 是否有 Disallow: /* 等通配符过度屏蔽',
                  '移除或修正过度屏蔽的 Disallow 规则，确保核心页面可被抓取',
                  'check_robots_no_wildcard_block'),
        make_rule('sitemap_format_valid', 'Sitemap XML 格式有效', 'crawl_index', 'important', 'medium',
                  '检查 sitemap.xml 是否为有效的 XML 格式',
                  '修复 sitemap 中的 XML 语法错误，确保符合 sitemap 协议规范',
                  'check_sitemap_format_valid'),
        make_rule('sitemap_url_count', 'Sitemap URL 数量不超 5 万', 'crawl_index', 'important', 'medium',
                  '检查单个 sitemap 文件的 URL 数量是否超过 50000',
                  '超过 50000 条的 sitemap 需拆分为多个 sitemap 并使用 sitemap index',
                  'check_sitemap_url_count'),
        make_rule('sitemap_gzip_support', 'Sitemap 支持压缩格式', 'crawl_index', 'info', 'low',
                  '检查是否提供 sitemap.xml.gz 压缩版本',
                  '提供 sitemap.xml.gz 可减少传输体积，提高抓取效率',
                  'check_sitemap_gzip_support'),
        make_rule('sitemap_lastmod_present', 'Sitemap URL 含 lastmod', 'crawl_index', 'info', 'low',
                  '检查 sitemap 中的 URL 是否包含 lastmod 更新时间',
                  '为 sitemap 中的 URL 添加 lastmod 字段，提示搜索引擎更新时间',
                  'check_sitemap_lastmod_present'),
        make_rule('sitemap_index_exists', 'Sitemap Index 配置合理', 'crawl_index', 'info', 'low',
                  '检查 sitemap index 是否正确引用子 sitemap',
                  '大型站点应使用 sitemap index 统一管理多个子 sitemap',
                  'check_sitemap_index_exists'),
        make_rule('http_403_forbidden', '无异常 403 封禁', 'crawl_index', 'important', 'medium',
                  '检查是否有大量页面返回 403 Forbidden',
                  '移除对正常页面的访问限制，确保搜索引擎可正常抓取',
                  'check_http_403_forbidden'),
        make_rule('http_410_gone', '410 Gone 页面标记合理', 'crawl_index', 'info', 'low',
                  '检查已删除页面是否返回 410 状态码（优于 404）',
                  '对已永久删除且不打算恢复的页面返回 410 Gone',
                  'check_http_410_gone'),
        make_rule('soft_404_detected', '无软 404 问题', 'crawl_index', 'important', 'high',
                  '检查是否存在 404 错误页返回 200 OK 状态码（软 404）',
                  '确保真实不存在的页面返回 404 或 410，而非 200 OK',
                  'check_soft_404_detected'),
        make_rule('redirect_chain_too_long', '重定向链超过 3 跳', 'crawl_index', 'important', 'high',
                  '检查 301/302 重定向链是否超过 3 次',
                  '合并重定向链，将源 URL 直接指向最终目标，减少中转',
                  'check_redirect_chain_too_long'),
        make_rule('redirect_loop_detected', '无重定向循环', 'crawl_index', 'critical', 'high',
                  '检查是否存在 A→B→A 的重定向循环',
                  '打破重定向循环，确保所有重定向最终可到达目标页',
                  'check_redirect_loop_detected'),
        make_rule('redirect_302_misused', '302 临时跳转不滥用', 'crawl_index', 'important', 'medium',
                  '检查是否有大量应当 301 的场景误用了 302',
                  '永久重定向应使用 301，只有临时跳转才使用 302/307',
                  'check_redirect_302_misused'),
        make_rule('redirect_mixed_usage', '301/302 不混用在同一条链', 'crawl_index', 'info', 'low',
                  '检查重定向链中是否同时混用了 301 和 302',
                  '一条重定向链中建议只使用同一种状态码，语义更清晰',
                  'check_redirect_mixed_usage'),
        make_rule('dns_resolvable', '域名 DNS 可正常解析', 'crawl_index', 'critical', 'high',
                  '检查网站域名 DNS 是否能正常解析',
                  '修复 DNS 解析配置，确保域名可稳定解析',
                  'check_dns_resolvable'),
        make_rule('ssl_certificate_valid', 'SSL 证书有效且未过期', 'crawl_index', 'critical', 'high',
                  '检查 SSL 证书是否有效、是否即将过期',
                  '及时更新即将过期的 SSL 证书，确保 HTTPS 正常工作',
                  'check_ssl_certificate_valid'),
        make_rule('internal_dead_links', '站内无死链（4xx/5xx）', 'crawl_index', 'important', 'high',
                  '检查站点内部是否存在指向 4xx/5xx 的死链',
                  '修复或移除死链，提高用户体验和搜索引擎信任度',
                  'check_internal_dead_links'),
        make_rule('slow_response_pages', '无响应时间超 3s 页面', 'crawl_index', 'important', 'medium',
                  '检查是否存在响应时间超过 3 秒的页面',
                  '优化慢查询、减少阻塞请求，确保首字节响应迅速',
                  'check_slow_response_pages'),
        make_rule('pagination_rel_next_prev', '分页含 rel=next/prev', 'crawl_index', 'info', 'low',
                  '检查分页列表页是否含 rel=next/prev 标签',
                  '为列表分页添加 rel="next" 和 rel="prev" 标明分页关系',
                  'check_pagination_rel_next_prev'),
        make_rule('meta_noindex_check', '重要页面不设 noindex', 'crawl_index', 'important', 'high',
                  '检查首页、分类页等重要页面是否被设为 noindex',
                  '移除重要页面的 noindex 标签，确保可被搜索引擎收录',
                  'check_meta_noindex_check'),
        make_rule('nofollow_internal_abuse', 'nofollow 未被滥用于内链', 'crawl_index', 'info', 'low',
                  '检查是否滥用 rel=nofollow 处理站内链接',
                  '内部链接不建议大量使用 nofollow，会阻碍权重传递',
                  'check_nofollow_internal_abuse'),
        make_rule('x_robots_tag_used', 'X-Robots-Tag 响应头合理', 'crawl_index', 'info', 'low',
                  '检查 X-Robots-Tag 响应头是否合理配置',
                  '如需使用响应头级抓取控制，确认规则正确且不影响收录',
                  'check_x_robots_tag_used'),
        make_rule('connect_timeout_none', '无连接超时页面', 'crawl_index', 'important', 'medium',
                  '检查是否有页面连接超时无法访问',
                  '修复服务器配置或移除无法访问的链接目标',
                  'check_connect_timeout_none'),
        make_rule('ssl_stapling_enabled', 'OCSP Stapling 启用', 'crawl_index', 'info', 'low',
                  '检查服务器是否启用了 OCSP Stapling',
                  '启用 OCSP Stapling 可提升 SSL 握手性能',
                  'check_ssl_stapling_enabled'),
        make_rule('http2_supported', 'HTTP/2 协议支持', 'crawl_index', 'info', 'low',
                  '检查服务器是否支持 HTTP/2 协议',
                  '升级 Web 服务器启用 HTTP/2，提升传输性能',
                  'check_http2_supported'),
        make_rule('ipv6_reachable', 'IPv6 可访问性', 'crawl_index', 'info', 'low',
                  '检查网站是否支持 IPv6 访问',
                  '为服务器配置 IPv6 地址和 AAAA 记录，面向未来网络',
                  'check_ipv6_reachable'),
        make_rule('canonical_status_ok', 'Canonical 指向页状态正常', 'crawl_index', 'important', 'medium',
                  '检查 canonical 指向的目标页是否 200 可访问',
                  '修正 canonical 目标，确保其为可访问的规范页面',
                  'check_canonical_status_ok'),
        make_rule('redirect_to_404', '重定向目标非 404', 'crawl_index', 'important', 'medium',
                  '检查是否存在重定向最终指向 404 的情况',
                  '删除指向 404 的重定向，或修正目标地址',
                  'check_redirect_to_404'),
        make_rule('maintenance_503_none', '无 503 维护模式残留', 'crawl_index', 'critical', 'high',
                  '检查是否有站点返回 503 Service Unavailable',
                  '结束维护后移除 503 响应，恢复正常服务',
                  'check_maintenance_503_none'),
    ]
    for r in additions:
        if r['id'] not in existing_ids:
            rules.append(r)
    return rules


# ========== 2. TDK（现有 10 → 目标 32） ==========
def build_tdk(existing):
    rules = list(existing)
    existing_ids = {r['id'] for r in rules}
    additions = [
        make_rule('title_has_keyword', 'Title 含主关键词', 'tdk', 'important', 'medium',
                  '检查 Title 中是否包含页面主关键词',
                  '将页面核心关键词放在 Title 靠前位置，提高相关性',
                  'check_title_has_keyword'),
        make_rule('title_has_brand', 'Title 末尾含品牌词', 'tdk', 'info', 'low',
                  '检查 Title 末尾是否包含品牌或站点名',
                  'Title 末尾加品牌词可提升品牌识别和点击率',
                  'check_title_has_brand'),
        make_rule('title_no_stopwords', 'Title 不含冗余停用词', 'tdk', 'info', 'low',
                  '检查 Title 是否存在过多无意义停用词',
                  '精简 Title，去除"首页"、"欢迎"等无价值词',
                  'check_title_no_stopwords'),
        make_rule('title_no_special_chars', 'Title 无特殊控制字符', 'tdk', 'info', 'low',
                  '检查 Title 是否含有未转义的特殊字符',
                  '清理 Title 中的控制字符和非法 Unicode，确保正确显示',
                  'check_title_no_special_chars'),
        make_rule('title_unique_sitewide', '全站 Title 无重复', 'tdk', 'important', 'high',
                  '检查全站 Title 是否存在重复',
                  '每个页面的 Title 应唯一，准确反映页面主题',
                  'check_title_unique_sitewide'),
        make_rule('description_has_keyword', 'Description 含主关键词', 'tdk', 'important', 'medium',
                  '检查 Description 是否包含页面主关键词',
                  '在 Description 中自然融入关键词，可被搜索引擎加粗高亮',
                  'check_description_has_keyword'),
        make_rule('description_has_cta', 'Description 含号召性用语 CTA', 'tdk', 'info', 'low',
                  '检查 Description 是否有号召性用语',
                  '加入"立即查看"、"免费试用"等 CTA 可提升点击率',
                  'check_description_has_cta'),
        make_rule('description_no_duplicate', '全站 Description 无重复', 'tdk', 'important', 'high',
                  '检查全站 Description 是否有重复',
                  '为每个页面定制 Description，避免默认模板复制',
                  'check_description_no_duplicate'),
        make_rule('description_no_punctuation_abuse', 'Description 标点不滥用', 'tdk', 'info', 'low',
                  '检查 Description 是否滥用标点或特殊符号',
                  '少用"★【】"等装饰符号，保持描述专业简洁',
                  'check_description_no_punctuation_abuse'),
        make_rule('keywords_not_stuffed', 'Keywords 未堆砌', 'tdk', 'important', 'medium',
                  '检查 meta keywords 是否堆砌了大量重复词',
                  'Keywords 只列 3-5 个真实相关词，现在搜索引擎权重很低',
                  'check_keywords_not_stuffed'),
        make_rule('keywords_count_reasonable', 'Keywords 数量合理（3-5 个）', 'tdk', 'info', 'low',
                  '检查 meta keywords 是否过多过少',
                  '建议 keywords 数量在 3-5 个之间，以逗号分隔',
                  'check_keywords_count_reasonable'),
        make_rule('keywords_comma_format', 'Keywords 逗号分隔格式正确', 'tdk', 'info', 'low',
                  '检查 keywords 是否正确使用英文逗号',
                  '关键词之间使用英文半角逗号分隔，不要用空格或顿号',
                  'check_keywords_comma_format'),
        make_rule('h1_title_consistent', 'H1 与 Title 主题一致', 'tdk', 'important', 'medium',
                  '检查页面 H1 与 Title 的核心主题是否一致',
                  'H1 与 Title 应围绕同一关键词主题，语义互相印证',
                  'check_h1_title_consistent'),
        make_rule('h1_title_not_identical', 'H1 与 Title 不完全相同', 'tdk', 'info', 'low',
                  '检查 H1 是否与 Title 完全一字不差',
                  'H1 可以与 Title 主题一致，但文案上应有所区分',
                  'check_h1_title_not_identical'),
        make_rule('og_title_complete', 'OG Title 完整', 'tdk', 'info', 'low',
                  '检查是否设置了 og:title 标签',
                  '补充 og:title 可优化社交分享时的标题展示',
                  'check_og_title_complete'),
        make_rule('og_description_complete', 'OG Description 完整', 'tdk', 'info', 'low',
                  '检查是否设置了 og:description 标签',
                  '补充 og:description 优化社交分享时的描述展示',
                  'check_og_description_complete'),
        make_rule('twitter_title_complete', 'Twitter Title 完整', 'tdk', 'info', 'low',
                  '检查是否设置了 twitter:title 标签',
                  '补充 twitter:title 优化 Twitter 卡片标题',
                  'check_twitter_title_complete'),
        make_rule('twitter_description_complete', 'Twitter Description 完整', 'tdk', 'info', 'low',
                  '检查是否设置了 twitter:description 标签',
                  '补充 twitter:description 优化 Twitter 卡片描述',
                  'check_twitter_description_complete'),
        make_rule('canonical_title_match', 'Canonical 与 Title 指向一致', 'tdk', 'info', 'low',
                  '检查 canonical 目标页的 Title 是否与本页一致',
                  'canonical 目标页 Title 应与当前页语义匹配',
                  'check_canonical_title_match'),
        make_rule('meta_robots_noindex', 'Meta Robots 未误设 noindex', 'tdk', 'important', 'high',
                  '检查 meta robots 标签是否误设 noindex',
                  '需要收录的页面不要设置 <meta name="robots" content="noindex">',
                  'check_meta_robots_noindex'),
        make_rule('meta_robots_nosnippet', 'Meta Robots 未设 nosnippet', 'tdk', 'info', 'low',
                  '检查是否设置了 nosnippet 阻止搜索引擎生成摘要',
                  '除非有特殊需求，否则不建议设置 nosnippet',
                  'check_meta_robots_nosnippet'),
        make_rule('meta_robots_noarchive', 'Meta Robots 未设 noarchive', 'tdk', 'info', 'low',
                  '检查是否设置了 noarchive 阻止网页存档',
                  '一般站点不建议设置 noarchive，允许搜索引擎存档',
                  'check_meta_robots_noarchive'),
    ]
    for r in additions:
        if r['id'] not in existing_ids:
            rules.append(r)
    return rules


# ========== 3. 内容质量（现有 11 → 目标 33） ==========
def build_content_quality(existing):
    rules = list(existing)
    existing_ids = {r['id'] for r in rules}
    additions = [
        make_rule('word_count_500_plus', '正文 ≥ 500 字（更优）', 'content_quality', 'info', 'medium',
                  '检查正文字数是否达到 500 字以上',
                  '优质内容建议 500 字以上，充分阐述主题',
                  'check_word_count_500_plus'),
        make_rule('word_count_1000_plus', '正文 ≥ 1000 字（深度）', 'content_quality', 'info', 'low',
                  '检查是否达到 1000 字深度长文标准',
                  '主题页和长文建议达到 1000+ 字，覆盖更全面信息',
                  'check_word_count_1000_plus'),
        make_rule('paragraph_length_reasonable', '段落长度合理（≤300 字）', 'content_quality', 'info', 'low',
                  '检查单段落字数是否过长',
                  '长段落拆分为短段落，提高可读性',
                  'check_paragraph_length_reasonable'),
        make_rule('avg_sentence_length', '平均句子长度合理', 'content_quality', 'info', 'low',
                  '检查平均每句字数是否过长',
                  '长句拆分为短句，避免读者难以理解',
                  'check_avg_sentence_length'),
        make_rule('heading_hierarchy_correct', '标题层级不跳级', 'content_quality', 'important', 'medium',
                  '检查是否从 H1 直接跳到 H3 等跳级现象',
                  '遵循 H1→H2→H3 的层级顺序，不要跨级',
                  'check_heading_hierarchy_correct'),
        make_rule('h2_has_multiple', '有多个 H2 支撑结构', 'content_quality', 'info', 'low',
                  '检查正文是否至少包含 2 个以上 H2 副标题',
                  '结构化的文章建议用多个 H2 分段阐述',
                  'check_h2_has_multiple'),
        make_rule('h3_usage_reasonable', 'H3 层级使用合理', 'content_quality', 'info', 'low',
                  '检查 H3 是否嵌套在对应 H2 之下使用',
                  'H3 应作为对应 H2 下的子标题使用',
                  'check_h3_usage_reasonable'),
        make_rule('keyword_first_paragraph', '首段出现主关键词', 'content_quality', 'important', 'medium',
                  '检查文章首段是否包含主关键词',
                  '在首段 100 字内自然融入主关键词',
                  'check_keyword_first_paragraph'),
        make_rule('keyword_in_h2', 'H2 含关键词', 'content_quality', 'info', 'medium',
                  '检查 H2 副标题中是否出现关键词',
                  '在部分 H2 中自然融入关键词或相关词',
                  'check_keyword_in_h2'),
        make_rule('keyword_density_not_zero', '关键词密度不为 0', 'content_quality', 'important', 'medium',
                  '检查页面主关键词是否完全未出现',
                  '在正文自然融入关键词，相关性为 0 的页面很难获得排名',
                  'check_keyword_density_not_zero'),
        make_rule('keyword_stuffing_risk', '无关键词堆砌风险（>10%）', 'content_quality', 'important', 'medium',
                  '检查关键词密度是否超过 10%，可能有堆砌',
                  '密度超过 10% 明显异常，需人工排查稀释',
                  'check_keyword_stuffing_risk'),
        make_rule('latent_semantic_keywords', '包含语义相关词（LSI）', 'content_quality', 'info', 'low',
                  '检查是否包含主关键词之外的相关语义词',
                  '加入行业相关词、同义词，提升搜索引擎语义理解',
                  'check_latent_semantic_keywords'),
        make_rule('image_count_reasonable', '图片数量合理', 'content_quality', 'info', 'low',
                  '检查页面是否包含适当数量的图片',
                  '适量配图可丰富内容，增强阅读体验',
                  'check_image_count_reasonable'),
        make_rule('image_dimensions_set', '图片含 width/height 属性', 'content_quality', 'info', 'medium',
                  '检查 img 标签是否包含宽高属性',
                  '为图片设置 width/height 可减少 CLS 布局偏移',
                  'check_image_dimensions_set'),
        make_rule('image_lazy_loaded', '图片启用懒加载', 'content_quality', 'info', 'low',
                  '检查首屏外图片是否设置了 lazyload',
                  '非首屏图片加 loading="lazy" 提升加载速度',
                  'check_image_lazy_loaded'),
        make_rule('image_webp_format', '图片 WebP 格式使用', 'content_quality', 'info', 'low',
                  '检查是否使用 WebP 等现代格式',
                  '使用 WebP/AVIF 可在相同画质下减少 30% 体积',
                  'check_image_webp_format'),
        make_rule('list_elements_used', '有序/无序列表使用', 'content_quality', 'info', 'low',
                  '检查是否使用 ul/ol 列表组织要点',
                  '用列表组织信息结构清晰，利于理解和 SEO',
                  'check_list_elements_used'),
        make_rule('table_elements_used', '表格使用合理', 'content_quality', 'info', 'low',
                  '检查是否使用 table 组织对比数据',
                  '对比性数据用表格呈现更易理解',
                  'check_table_elements_used'),
        make_rule('blockquote_used', '引用块标记使用', 'content_quality', 'info', 'low',
                  '检查是否使用 blockquote 标记引用内容',
                  '引用内容用 blockquote 标明来源和版权',
                  'check_blockquote_used'),
        make_rule('video_embed_quality', '视频嵌入相关', 'content_quality', 'info', 'low',
                  '检查是否有相关视频内容嵌入',
                  '适当加入视频内容可延长停留时间',
                  'check_video_embed_quality'),
        make_rule('content_not_duplicate', '站内无重复内容', 'content_quality', 'important', 'high',
                  '检查是否与站内其他页面内容高度相似',
                  '确保每个页面内容独特，不与他页重复',
                  'check_content_not_duplicate'),
        make_rule('content_thin_page', '非薄内容页（<200 字）', 'content_quality', 'important', 'high',
                  '检查是否为字数极低的薄内容页',
                  '薄内容页建议补充更多有价值的信息或合并',
                  'check_content_thin_page'),
        make_rule('content_iframe_not_abused', 'iframe 未滥用', 'content_quality', 'info', 'low',
                  '检查是否大量使用 iframe 嵌入内容',
                  'iframe 内容搜索引擎难以抓取，尽量少用',
                  'check_content_iframe_not_abused'),
        make_rule('content_noscript_used', 'noscript 标签使用', 'content_quality', 'info', 'low',
                  '检查 noscript 是否提供了 JS 内容的降级',
                  '依赖 JS 的内容补充 noscript 版本供抓取',
                  'check_content_noscript_used'),
        make_rule('anchor_text_variety', '内链锚文本多样化', 'content_quality', 'info', 'low',
                  '检查内链锚文本是否过于单一',
                  '内链锚文本使用多样化，不要全站都用同一个词',
                  'check_anchor_text_variety'),
        make_rule('external_links_authoritative', '外链指向权威站点', 'content_quality', 'info', 'medium',
                  '检查外链是否指向高质量权威站点',
                  '适量引用权威来源链接，提升内容可信度',
                  'check_external_links_authoritative'),
        make_rule('broken_external_links', '无死外链', 'content_quality', 'important', 'medium',
                  '检查外部链接是否存在 4xx/5xx 死链',
                  '定期检查外链可访问性，移除失效链接',
                  'check_broken_external_links'),
        make_rule('external_links_nofollow', '外链合理使用 nofollow', 'content_quality', 'info', 'low',
                  '检查付费/广告外链是否加 nofollow',
                  '商业合作、付费外链必须加 rel="nofollow" 或 sponsored',
                  'check_external_links_nofollow'),
        make_rule('content_no_flash', '不使用 Flash 内容', 'content_quality', 'info', 'low',
                  '检查是否仍使用 Flash 插件',
                  '现代浏览器不再支持 Flash，全部替换为 HTML5',
                  'check_content_no_flash'),
        make_rule('internal_link_diversity', '内链指向页面多样', 'content_quality', 'info', 'low',
                  '检查内链是否只指向少数几个页面',
                  '内链应覆盖相关主题页，形成良好的内链网络',
                  'check_internal_link_diversity'),
        make_rule('flesch_readable', 'Flesch 可读性达标', 'content_quality', 'info', 'low',
                  '基于句长和词长评估内容可读性',
                  '复杂术语配合解释，让内容易懂',
                  'check_flesch_readable'),
        make_rule('content_has_summary', '文章有结论/总结段', 'content_quality', 'info', 'low',
                  '检查长文末尾是否有总结性段落',
                  '文末总结帮读者快速回顾要点',
                  'check_content_has_summary'),
    ]
    for r in additions:
        if r['id'] not in existing_ids:
            rules.append(r)
    return rules


# ========== 4. 技术 SEO（现有 14 → 目标 33） ==========
def build_technical_seo(existing):
    rules = list(existing)
    existing_ids = {r['id'] for r in rules}
    additions = [
        make_rule('https_mixed_content_none', '无 HTTPS 混合内容', 'technical_seo', 'important', 'medium',
                  '检查 HTTPS 页是否引用了 HTTP 的资源',
                  '将所有资源引用改为 HTTPS，避免混合内容警告',
                  'check_https_mixed_content_none'),
        make_rule('tls_modern_version', 'TLS 版本 ≥ 1.2', 'technical_seo', 'info', 'medium',
                  '检查服务器 TLS 协议版本',
                  '禁用旧 TLS 1.0/1.1，只保留 TLS 1.2 及以上',
                  'check_tls_modern_version'),
        make_rule('ssl_not_expiring_soon', 'SSL 证书不过期（>30天）', 'technical_seo', 'important', 'high',
                  '检查 SSL 证书剩余有效期',
                  '证书到期前及时续费，避免 HTTPS 失效',
                  'check_ssl_not_expiring_soon'),
        make_rule('www_non_www_canonical', 'www 与非 www 规范化', 'technical_seo', 'important', 'high',
                  '检查 www 和非 www 是否统一 301 到主版本',
                  '选择带 www 或不带 www 其一作为主域名，统一 301',
                  'check_www_non_www_canonical'),
        make_rule('trailing_slash_canonical', '结尾斜杠规范化', 'technical_seo', 'info', 'medium',
                  '检查 URL 是否同时支持带 / 和不带 / 的访问',
                  '二选一作为规范版本，另一个 301 跳过去',
                  'check_trailing_slash_canonical'),
        make_rule('case_sensitive_url', 'URL 大小写规范化', 'technical_seo', 'info', 'medium',
                  '检查 URL 大小写不敏感是否统一',
                  '建议统一使用小写 URL，大写版本 301 到小写',
                  'check_case_sensitive_url'),
        make_rule('amp_version_present', 'AMP 版本配置（适用时）', 'technical_seo', 'info', 'low',
                  '检查是否配置了 AMP 加速移动页面',
                  '新闻/资讯类站点可配置 AMP 版本，提高移动端速度',
                  'check_amp_version_present'),
        make_rule('pwa_manifest_present', 'PWA manifest.json', 'technical_seo', 'info', 'low',
                  '检查是否配置了 PWA 应用清单',
                  '配置 manifest.json 可支持"添加到主屏"',
                  'check_pwa_manifest_present'),
        make_rule('rel_alternate_mobile', 'rel=alternate 移动版配置', 'technical_seo', 'info', 'low',
                  '检查是否配置了移动版专用的 rel=alternate',
                  '如存在 m 站移动版，通过 rel=alternate 标明关系',
                  'check_rel_alternate_mobile'),
        make_rule('pagination_canonical_correct', '分页 canonical 正确', 'technical_seo', 'important', 'medium',
                  '检查分页页是否设置了错误的 canonical',
                  '分页各页的 canonical 应指向自身，或 all-in-one 视图',
                  'check_pagination_canonical_correct'),
        make_rule('pagination_noindex_first_only', '分页不要只 noindex 第一页', 'technical_seo', 'info', 'low',
                  '检查是否错误地 noindex 了列表第一页',
                  '第一页通常是重要着陆页，不要 noindex',
                  'check_pagination_noindex_first_only'),
        make_rule('hreflang_self_referential', 'hreflang 自引用', 'technical_seo', 'info', 'medium',
                  '检查每个语言版本是否 hreflang 引用了自身',
                  'hreflang 必须包含"x→x"的自引用，否则会被忽略',
                  'check_hreflang_self_referential'),
        make_rule('hreflang_return_tags', 'hreflang 返回标签双向', 'technical_seo', 'info', 'medium',
                  '检查 hreflang 是否有双向返回关系',
                  'A→B 的 hreflang 必须有对应 B→A 的返回标签',
                  'check_hreflang_return_tags'),
        make_rule('hreflang_x_default', 'hreflang x-default 配置', 'technical_seo', 'info', 'low',
                  '检查是否配置了 hreflang x-default 回退版本',
                  '多语言站点建议设置 x-default 作为默认回退页',
                  'check_hreflang_x_default'),
        make_rule('soft_404_custom_page', '404 页为真 404 + 自定义内容', 'technical_seo', 'important', 'high',
                  '检查 404 页是否返回真 404 且有引导内容',
                  '404 页返回 404 状态码，并提供搜索框/导航引导用户',
                  'check_soft_404_custom_page'),
        make_rule('http2_https_support', 'HTTPS 支持 HTTP/2', 'technical_seo', 'info', 'low',
                  '检查 HTTPS 是否启用 HTTP/2',
                  'HTTP/2 多路复用可显著减少加载时间',
                  'check_http2_https_support'),
        make_rule('ipv6_dns_record', 'IPv6 AAAA 记录配置', 'technical_seo', 'info', 'low',
                  '检查是否有 IPv6 AAAA 记录',
                  '配置 IPv6 面向未来网络，新用户已占不小比例',
                  'check_ipv6_dns_record'),
        make_rule('ga_tracking_present', 'Google Analytics 代码已安装', 'technical_seo', 'info', 'low',
                  '检查是否安装了 GA 或 GTM 统计代码',
                  '安装流量统计代码以监控 SEO 优化效果',
                  'check_ga_tracking_present'),
        make_rule('gsc_verification', 'Google Search Console 验证', 'technical_seo', 'info', 'low',
                  '检查是否有 GSC 验证标记',
                  '通过 HTML 标记或 DNS 验证 GSC，获取官方数据',
                  'check_gsc_verification'),
        make_rule('gtm_installed', 'Google Tag Manager 已部署', 'technical_seo', 'info', 'low',
                  '检查是否部署了 GTM 容器',
                  '使用 GTM 管理各类跟踪代码，修改无需改代码',
                  'check_gtm_installed'),
        make_rule('privacy_policy_link', '隐私政策链接存在', 'technical_seo', 'important', 'medium',
                  '检查网站是否有隐私政策页面链接',
                  '在页脚放置隐私政策链接，符合 GDPR 等法规',
                  'check_privacy_policy_link'),
        make_rule('cookie_consent_banner', 'Cookie 同意提示', 'technical_seo', 'important', 'medium',
                  '检查是否有 Cookie 同意弹窗',
                  '面向欧盟/加州用户的站点需符合 GDPR/CCPA',
                  'check_cookie_consent_banner'),
        make_rule('sitemap_in_robots_duplicate', 'robots.txt 与 GSC 同时提交 sitemap', 'technical_seo', 'info', 'low',
                  '建议在 robots.txt 和 GSC 两处都提交 sitemap',
                  '在 GSC 手动提交 sitemap 比只放 robots.txt 更有效',
                  'check_sitemap_in_robots_duplicate'),
        make_rule('404_200_status_conflict', '404 页不返回 200', 'technical_seo', 'critical', 'high',
                  '检查 404 页是否被误返回 200 OK（软 404）',
                  '务必让不存在的页面返回真 404 状态码',
                  'check_404_200_status_conflict'),
        make_rule('cdn_enabled', 'CDN 加速启用', 'technical_seo', 'important', 'medium',
                  '检查静态资源是否走 CDN',
                  '接入 CDN 加速静态资源分发，显著提升访问速度',
                  'check_cdn_enabled'),
        make_rule('dns_prefetch_configured', 'DNS Prefetch 配置', 'technical_seo', 'info', 'low',
                  '检查是否配置了 dns-prefetch',
                  '对常用第三方域名进行 DNS 预解析，节省握手时间',
                  'check_dns_prefetch_configured'),
        make_rule('preconnect_3rd_party', 'Preconnect 第三方域名', 'technical_seo', 'info', 'low',
                  '检查是否对关键第三方域名 preconnect',
                  '对 GTM、GA、字体等第三方域名使用 preconnect',
                  'check_preconnect_3rd_party'),
        make_rule('cors_headers_correct', 'CORS 响应头正确', 'technical_seo', 'info', 'low',
                  '检查 CORS 响应头是否过宽',
                  'CORS Access-Control-Allow-Origin 不要设为 * 如非必要',
                  'check_cors_headers_correct'),
        make_rule('security_headers_present', '完整安全响应头', 'technical_seo', 'important', 'medium',
                  '检查 CSP、Referrer-Policy、Permissions-Policy 等',
                  '配置完整安全响应头，提升站点安全评级',
                  'check_security_headers_present'),
    ]
    for r in additions:
        if r['id'] not in existing_ids:
            rules.append(r)
    return rules


# ========== 5. 性能优化（现有 8 → 目标 28） ==========
def build_performance(existing):
    rules = list(existing)
    existing_ids = {r['id'] for r in rules}
    additions = [
        make_rule('ttfb_fast', '首字节时间 TTFB < 600ms', 'performance', 'important', 'high',
                  '检查 Time To First Byte 是否合格',
                  '优化后端响应逻辑、数据库查询、缓存策略',
                  'check_ttfb_fast'),
        make_rule('ttfb_excellent', 'TTFB < 200ms（优秀）', 'performance', 'info', 'low',
                  '检查 TTFB 是否达到优秀水平',
                  '全页面缓存 + CDN + 边缘计算可达到极致 TTFB',
                  'check_ttfb_excellent'),
        make_rule('fcp_fast', 'FCP 首次内容绘制 < 1.8s', 'performance', 'important', 'high',
                  '检查 First Contentful Paint 指标',
                  '减少阻塞的 CSS/JS，提升首屏绘制',
                  'check_fcp_fast'),
        make_rule('speed_index_good', 'Speed Index < 3.4s', 'performance', 'important', 'medium',
                  '检查 Speed Index 指标',
                  '优化渲染顺序，优先展示主内容',
                  'check_speed_index_good'),
        make_rule('tti_fast', '可交互时间 TTI < 3.8s', 'performance', 'important', 'medium',
                  '检查 Time to Interactive',
                  '减少 JS 体积和执行时间，提升可交互速度',
                  'check_tti_fast'),
        make_rule('tbt_low', '总阻塞时间 TBT < 200ms', 'performance', 'important', 'medium',
                  '检查 Total Blocking Time',
                  '拆分长任务，延迟执行非关键 JS',
                  'check_tbt_low'),
        make_rule('image_optimized', '图片压缩优化充分', 'performance', 'important', 'medium',
                  '检查页面图片是否经过压缩',
                  '压缩图片大小、选择合理尺寸和格式',
                  'check_image_optimized'),
        make_rule('image_format_modern', '现代图片格式（WebP/AVIF）', 'performance', 'info', 'medium',
                  '检查是否使用 WebP、AVIF 现代格式',
                  '使用 WebP 或 AVIF，在同画质下体积减少约 25-50%',
                  'check_image_format_modern'),
        make_rule('js_execution_fast', 'JS 执行时间 < 3.5s', 'performance', 'important', 'medium',
                  '检查主 JS 执行总时长',
                  '代码分割、Tree Shaking、移除无用依赖',
                  'check_js_execution_fast'),
        make_rule('unused_css_removed', '未使用 CSS 已移除', 'performance', 'info', 'medium',
                  '检查是否存在大量未使用的 CSS 规则',
                  '通过 PurgeCSS 等工具移除未使用 CSS',
                  'check_unused_css_removed'),
        make_rule('unused_js_removed', '未使用 JS 已移除', 'performance', 'info', 'medium',
                  '检查是否存在未使用的 JS 代码块',
                  '代码分割 + Tree Shaking，按需加载模块',
                  'check_unused_js_removed'),
        make_rule('dom_size_reasonable', 'DOM 节点数 < 1500', 'performance', 'important', 'medium',
                  '检查 DOM 节点总数是否过多',
                  '扁平化 DOM 结构，减少嵌套层级',
                  'check_dom_size_reasonable'),
        make_rule('dom_depth_reasonable', 'DOM 最大深度 ≤ 32', 'performance', 'info', 'low',
                  '检查 DOM 嵌套深度是否超标',
                  '减少不必要的容器 div 嵌套',
                  'check_dom_depth_reasonable'),
        make_rule('critical_request_chain_short', '关键请求链短', 'performance', 'info', 'medium',
                  '检查关键渲染路径的请求链深度',
                  '减少串行请求依赖，合并关键资源',
                  'check_critical_request_chain_short'),
        make_rule('third_party_scripts_limited', '第三方脚本 < 5 个', 'performance', 'important', 'medium',
                  '检查页面加载的第三方脚本数量',
                  '只保留必要第三方脚本，异步延迟加载',
                  'check_third_party_scripts_limited'),
        make_rule('font_display_swap', '字体配置 font-display', 'performance', 'important', 'low',
                  '检查 @font-face 是否配置 font-display: swap',
                  '设置 font-display 避免隐形文字闪烁 (FOIT)',
                  'check_font_display_swap'),
        make_rule('font_fout_minimized', 'FOUT 无样式文字问题已处理', 'performance', 'info', 'low',
                  '检查 FOUT 问题是否严重',
                  '预加载关键字体、使用 font-display: swap',
                  'check_font_fout_minimized'),
        make_rule('preconnect_used', 'preconnect 预连接使用', 'performance', 'info', 'low',
                  '检查是否对关键域名使用 preconnect',
                  '对关键域名使用 <link rel=preconnect> 提前握手',
                  'check_preconnect_used'),
        make_rule('preload_critical', '关键资源 preload', 'performance', 'info', 'medium',
                  '检查是否对关键 CSS/字体使用 preload',
                  '对首屏必须的资源用 <link rel=preload> 预加载',
                  'check_preload_critical'),
        make_rule('prefetch_prerender_used', 'Prefetch/Prerender 合理使用', 'performance', 'info', 'low',
                  '检查是否对后续页面资源使用 prefetch',
                  '对极可能访问的下一个页面使用 prefetch',
                  'check_prefetch_prerender_used'),
        make_rule('long_tasks_avoided', '无 >50ms 的长任务', 'performance', 'important', 'medium',
                  '检查是否存在超过 50ms 的长任务',
                  '拆分长任务，使用 requestIdleCallback 处理非紧急逻辑',
                  'check_long_tasks_avoided'),
        make_rule('main_thread_work_low', '主线程工作量合理', 'performance', 'info', 'medium',
                  '检查主线程总工作量',
                  '把非 UI 计算移到 Web Worker，减少主线程占用',
                  'check_main_thread_work_low'),
        make_rule('service_worker_registered', 'Service Worker 注册', 'performance', 'info', 'low',
                  '检查是否注册 Service Worker 做离线缓存',
                  '注册 SW 可实现离线访问和资源缓存，提升二次访问速度',
                  'check_service_worker_registered'),
        make_rule('text_compression_enabled', '文本压缩已启用', 'performance', 'important', 'high',
                  '检查 HTML/CSS/JS 是否启用 Gzip 或 Brotli',
                  '在服务器上启用 Gzip 或 Brotli 压缩文本类资源',
                  'check_text_compression_enabled'),
        make_rule('cdn_static_resources', '静态资源走 CDN', 'performance', 'info', 'medium',
                  '检查 CSS/JS/图片等静态资源是否走 CDN',
                  '静态资源都放到 CDN，实现边缘加速',
                  'check_cdn_static_resources'),
        make_rule('responsive_images_srcset', '响应式图片 srcset', 'performance', 'info', 'low',
                  '检查 img 是否使用 srcset 提供多尺寸图',
                  '用 srcset + sizes 让浏览器按设备选合适尺寸',
                  'check_responsive_images_srcset'),
    ]
    for r in additions:
        if r['id'] not in existing_ids:
            rules.append(r)
    return rules


# ========== 6. 移动友好（现有 8 → 目标 28） ==========
def build_mobile(existing):
    rules = list(existing)
    existing_ids = {r['id'] for r in rules}
    additions = [
        make_rule('viewport_width_device', 'Viewport width=device-width', 'mobile', 'critical', 'high',
                  '检查 viewport 是否正确设置 width=device-width',
                  '<meta name=viewport content="width=device-width, initial-scale=1">',
                  'check_viewport_width_device'),
        make_rule('viewport_no_user_scalable_no', '未禁用 user-scalable', 'mobile', 'important', 'medium',
                  '检查是否设置了 user-scalable=no 禁止缩放',
                  '不要禁用用户缩放，保持可访问性',
                  'check_viewport_no_user_scalable_no'),
        make_rule('viewport_maximum_scale', '未设 maximum-scale 限制缩放', 'mobile', 'info', 'low',
                  '检查是否设置了 maximum-scale 限制放大',
                  '不要限制 maximum-scale，保持用户可放大能力',
                  'check_viewport_maximum_scale'),
        make_rule('small_screen_360_ok', '360px 小屏适配正常', 'mobile', 'important', 'medium',
                  '检查 360px 宽度下是否有横向滚动',
                  '使用 media query 对小屏进行适配',
                  'check_small_screen_360_ok'),
        make_rule('font_size_mobile_14px', '移动端正文 ≥ 14px', 'mobile', 'important', 'medium',
                  '检查移动端正文字体是否小于 14px',
                  '移动端正文建议 14px 以上，确保可读性',
                  'check_font_size_mobile_14px'),
        make_rule('line_height_mobile_ok', '移动端行高 ≥ 1.5', 'mobile', 'info', 'low',
                  '检查移动端行高是否足够',
                  '移动端行高 1.5-1.6 更易阅读',
                  'check_line_height_mobile_ok'),
        make_rule('tap_target_size_48', '触摸元素尺寸 ≥ 48x48px', 'mobile', 'important', 'medium',
                  '检查按钮/链接触摸区域是否足够大',
                  '触摸元素建议至少 48x48px，方便手指点击',
                  'check_tap_target_size_48'),
        make_rule('tap_target_spacing_8', '触摸元素间距 ≥ 8px', 'mobile', 'important', 'medium',
                  '检查可点击元素之间的间距',
                  '元素间距至少 8px，避免误触',
                  'check_tap_target_spacing_8'),
        make_rule('no_flash_or_applets', '无 Flash/Java 插件内容', 'mobile', 'info', 'low',
                  '检查移动端是否仍使用旧插件',
                  '移动端完全不支持 Flash，全部替换为 HTML5',
                  'check_no_flash_or_applets'),
        make_rule('popup_not_obstructing', '弹窗不遮挡主内容', 'mobile', 'important', 'medium',
                  '检查首屏弹窗是否过大遮挡主内容',
                  '移动端弹窗建议使用底部抽屉或顶部横幅',
                  'check_popup_not_obstructing'),
        make_rule('popup_close_easy', '弹窗关闭按钮大且明显', 'mobile', 'info', 'low',
                  '检查弹窗是否容易关闭',
                  '关闭按钮放在显眼位置，尺寸足够大',
                  'check_popup_close_easy'),
        make_rule('img_responsive_width', '响应式图片自适应宽度', 'mobile', 'important', 'medium',
                  '检查图片是否会超出视口宽度',
                  '对所有图片设置 max-width: 100%，不撑破屏幕',
                  'check_img_responsive_width'),
        make_rule('no_horizontal_scroll', '无横向滚动条', 'mobile', 'important', 'high',
                  '检查移动端页面是否出现横向滚动',
                  '确保所有内容在屏幕宽度内，不出现横向滚动',
                  'check_no_horizontal_scroll'),
        make_rule('fixed_elements_width_ok', 'Fixed 元素宽度不超标', 'mobile', 'info', 'medium',
                  '检查 fixed 定位元素是否会导致横向溢出',
                  'fixed 元素宽度不要超过视口，加 left/right 限制',
                  'check_fixed_elements_width_ok'),
        make_rule('buttons_mobile_size', '移动端按钮尺寸合适', 'mobile', 'info', 'medium',
                  '检查 <button> 尺寸是否在移动端合理',
                  '按钮在移动端至少应保持 44px 高和足够的内边距',
                  'check_buttons_mobile_size'),
        make_rule('form_input_autocorrect', '表单输入框属性合理', 'mobile', 'info', 'low',
                  '检查 input 是否合理设置 autocorrect 等',
                  '电话、邮箱、地址等输入使用对应 inputmode',
                  'check_form_input_autocorrect'),
        make_rule('mobile_navigation_accessible', '移动端导航易访问', 'mobile', 'info', 'medium',
                  '检查汉堡菜单是否易打开',
                  '汉堡菜单放在标准位置（右上角），尺寸大',
                  'check_mobile_navigation_accessible'),
        make_rule('touch_active_feedback', '触摸状态 :active 反馈', 'mobile', 'info', 'low',
                  '检查 :active 伪类是否有视觉反馈',
                  '给按钮和链接设置 :active 状态，告诉用户已触发',
                  'check_touch_active_feedback'),
        make_rule('inputmode_attribute_set', 'inputmode 属性已设置', 'mobile', 'info', 'low',
                  '检查输入框是否配置 inputmode',
                  '数字、邮箱、电话等输入框用 inputmode 弹对应键盘',
                  'check_inputmode_attribute_set'),
        make_rule('orientation_landscape_ok', '横屏适配正常', 'mobile', 'info', 'low',
                  '检查横屏模式下页面是否正常',
                  '为横屏和竖屏都进行合理适配',
                  'check_orientation_landscape_ok'),
        make_rule('tel_links_used', '电话号码用 tel: 链接', 'mobile', 'important', 'low',
                  '检查页面上的电话号码是否加了 tel: 链接',
                  '显示的电话号码用 <a href="tel:xxx"> 包裹，支持一键拨号',
                  'check_tel_links_used'),
        make_rule('mailto_links_used', '邮箱用 mailto: 链接', 'mobile', 'info', 'low',
                  '检查邮箱地址是否加了 mailto:',
                  '邮箱地址用 <a href="mailto:xxx"> 一键发送邮件',
                  'check_mailto_links_used'),
        make_rule('responsive_breakpoints', '响应式断点覆盖主流设备', 'mobile', 'info', 'medium',
                  '检查 media query 断点是否覆盖 320/768/1024',
                  '至少覆盖 360/768/1024 三个主流断点',
                  'check_responsive_breakpoints'),
        make_rule('flex_or_grid_used', 'Flex/Grid 现代布局', 'mobile', 'info', 'low',
                  '检查布局是否使用 Flex/Grid 而非 float',
                  'Flex/Grid 天然支持响应式，比 float 更健壮',
                  'check_flex_or_grid_used'),
        make_rule('mobile_first_css', 'Mobile First CSS 写法', 'mobile', 'info', 'low',
                  '检查 CSS 是否为移动优先写法',
                  '默认样式针对小屏，大屏用 min-width 扩展',
                  'check_mobile_first_css'),
    ]
    for r in additions:
        if r['id'] not in existing_ids:
            rules.append(r)
    return rules


# ========== 7. 结构化数据（现有 9 → 目标 25） ==========
def build_structured_data(existing):
    rules = list(existing)
    existing_ids = {r['id'] for r in rules}
    additions = [
        make_rule('jsonld_single_type_consistent', 'JSON-LD @type 字段一致', 'structured_data', 'info', 'medium',
                  '检查 JSON-LD 是否包含合法的 @type 字段',
                  '确保每个 JSON-LD 块都有 @context 和 @type',
                  'check_jsonld_single_type_consistent'),
        make_rule('jsonld_context_correct', 'JSON-LD @context 正确', 'structured_data', 'important', 'medium',
                  '检查 JSON-LD @context 是否为 schema.org 官方',
                  '"@context": "https://schema.org" 是唯一合法值',
                  'check_jsonld_context_correct'),
        make_rule('jsonld_no_duplicate_blocks', 'JSON-LD 无重复定义', 'structured_data', 'info', 'low',
                  '检查是否重复声明了同类 schema',
                  '同一页面同类 schema 尽量合并到一个 JSON-LD 块',
                  'check_jsonld_no_duplicate_blocks'),
        make_rule('jsonld_not_empty', 'JSON-LD 非空有实际字段', 'structured_data', 'info', 'medium',
                  '检查 JSON-LD 是否为空壳只有 type',
                  '填充必要属性，如 name/description/image 等',
                  'check_jsonld_not_empty'),
        make_rule('microdata_format_used', 'Microdata 格式兼容', 'structured_data', 'info', 'low',
                  '检查是否除 JSON-LD 外还有 Microdata 标记',
                  'JSON-LD 是推荐写法，Microdata 亦可接受',
                  'check_microdata_format_used'),
        make_rule('rdfa_format_used', 'RDFa 格式兼容', 'structured_data', 'info', 'low',
                  '检查是否使用 RDFa 格式结构化标记',
                  'RDFa 也是合法格式，但 JSON-LD 更推荐',
                  'check_rdfa_format_used'),
        make_rule('product_schema_present', 'Product 产品 Schema', 'structured_data', 'info', 'medium',
                  '电商产品页是否有 Product 类型',
                  '产品页添加 Product Schema，可展示价格库存评分',
                  'check_product_schema_present'),
        make_rule('review_schema_present', 'Review 评论 Schema', 'structured_data', 'info', 'medium',
                  '有评论的页面是否添加 Review Schema',
                  '评论内容添加 Review/ReviewRating，展示星级',
                  'check_review_schema_present'),
        make_rule('rating_schema_in_range', 'Rating 评分范围合理', 'structured_data', 'important', 'low',
                  '检查 ratingValue 是否在 worstRating-bestRating 内',
                  '评分值必须在声明的范围之内，否则不予显示',
                  'check_rating_schema_in_range'),
        make_rule('event_schema_present', 'Event 活动 Schema', 'structured_data', 'info', 'low',
                  '活动页是否配置 Event 结构化数据',
                  '线下/线上活动页面添加 Event Schema',
                  'check_event_schema_present'),
        make_rule('course_schema_present', 'Course 课程 Schema', 'structured_data', 'info', 'low',
                  '教育类页面是否配置 Course Schema',
                  '课程页添加 Course 和 CourseInstance Schema',
                  'check_course_schema_present'),
        make_rule('job_schema_present', 'JobPosting 职位 Schema', 'structured_data', 'info', 'low',
                  '招聘页是否配置职位结构化数据',
                  '职位详情页添加 JobPosting Schema 进入 Google for Jobs',
                  'check_job_schema_present'),
        make_rule('sitelinks_searchbox', 'Sitelinks Searchbox 搜索框', 'structured_data', 'important', 'low',
                  '首页是否配置 WebSite + SearchAction',
                  '配置后搜索结果中可能直接显示站内搜索框',
                  'check_sitelinks_searchbox'),
        make_rule('corporate_contact', 'Corporate Contact 企业联系', 'structured_data', 'info', 'low',
                  '企业站是否配置 Organization + ContactPoint',
                  '企业联系电话、客服等用结构化数据声明',
                  'check_corporate_contact'),
        make_rule('logo_schema_present', 'Logo 结构化标记', 'structured_data', 'info', 'low',
                  'Organization 中是否声明了 logo',
                  '通过 Organization Schema 声明品牌官方 Logo URL',
                  'check_logo_schema_present'),
        make_rule('carousel_markup_valid', 'Carousel 轮播标记', 'structured_data', 'info', 'low',
                  '列表页是否配置 ItemList Carousel 标记',
                  '让 Google 理解内容序列，可能以轮播形式展示',
                  'check_carousel_markup_valid'),
        make_rule('howto_schema_present', 'HowTo 教程步骤 Schema', 'structured_data', 'info', 'low',
                  '教程类页面是否配置 HowTo Schema',
                  '一步步教操作的页面配置 HowTo，有专属富结果',
                  'check_howto_schema_present'),
        make_rule('recipe_schema_present', 'Recipe 食谱 Schema', 'structured_data', 'info', 'low',
                  '食谱页面是否配置 Recipe Schema',
                  '食谱站可配置 Recipe，展示时间、评分、卡路里',
                  'check_recipe_schema_present'),
        make_rule('video_schema_present', 'VideoObject 视频 Schema', 'structured_data', 'info', 'medium',
                  '含视频的页面是否配置 VideoObject',
                  '声明视频缩略图、时长、上传日期，支持视频缩略图',
                  'check_video_schema_present'),
        make_rule('social_profile_sameas', 'Social Profile sameAs 链接', 'structured_data', 'info', 'low',
                  'Organization 中是否列出社交媒体',
                  '用 sameAs 列出官微、官博等社交账号',
                  'check_social_profile_sameas'),
        make_rule('speakable_property_present', 'speakable 属性（新闻适用）', 'structured_data', 'info', 'low',
                  '新闻页是否配置 speakable 适合语音朗读',
                  '新闻类站点可配置 speakable，支持 Google Assistant 朗读',
                  'check_speakable_property_present'),
        make_rule('mainentity_of_page', 'mainEntityOfPage 声明', 'structured_data', 'info', 'low',
                  '检查是否使用 mainEntityOfPage 指明主实体',
                  '用 mainEntityOfPage 告诉 Google 页面对应的主实体',
                  'check_mainentity_of_page'),
    ]
    for r in additions:
        if r['id'] not in existing_ids:
            rules.append(r)
    return rules


def main():
    builders = {
        'crawl_index.json': build_crawl_index,
        'tdk.json': build_tdk,
        'content_quality.json': build_content_quality,
        'technical_seo.json': build_technical_seo,
        'performance.json': build_performance,
        'mobile.json': build_mobile,
        'structured_data.json': build_structured_data,
    }
    total = 0
    for fn, builder in builders.items():
        path = os.path.join(BASE, fn)
        with open(path, 'r', encoding='utf-8') as f:
            existing = json.load(f)
        new_rules = builder(existing)
        with open(path, 'w', encoding='utf-8') as f:
            json.dump(new_rules, f, ensure_ascii=False, indent=2)
        print(f'{fn}: {len(existing)} → {len(new_rules)}')
        total += len(new_rules)
    print(f'TOTAL: {total}')


if __name__ == '__main__':
    main()
